import type { AppSnapshot } from "./types.js";

export const sampleSnapshot: AppSnapshot = {
  syncState: "idle",
  tasks: [
    {
      id: "task-aime-spec",
      larkRecordId: "rec_aime_spec",
      title: "Review Aime desktop companion spec",
      sourceType: "meeting_note",
      sourceUrl: "https://bytedance.larkoffice.com/base/F4k1bKUkRaIafPsKxP2cVAyEnwJ",
      status: "open",
      dueDate: "2026-06-23",
      createdAt: "2026-06-23T09:00:00.000Z",
      updatedAt: "2026-06-23T09:00:00.000Z",
      project: "Aime Desktop",
    },
    {
      id: "task-aime-widget",
      larkRecordId: "rec_aime_widget",
      title: "Build floating widget prototype",
      sourceType: "manual",
      status: "open",
      dueDate: "2026-06-24",
      createdAt: "2026-06-23T09:00:00.000Z",
      updatedAt: "2026-06-23T09:00:00.000Z",
      project: "Aime Desktop",
    },
    {
      id: "task-aime-sync",
      larkRecordId: "rec_aime_sync",
      title: "Map Lark Base fields for sync",
      sourceType: "group_chat",
      status: "done",
      dueDate: "2026-06-22",
      createdAt: "2026-06-22T09:00:00.000Z",
      updatedAt: "2026-06-23T09:00:00.000Z",
      project: "Aime Desktop",
    },
  ],
  localMeta: [
    {
      taskId: "task-aime-spec",
      pinned: true,
      hidden: false,
      displayPriority: 3,
      reminderMinutesBefore: 60,
    },
    { taskId: "task-aime-widget", pinned: false, hidden: false, displayPriority: 2 },
    { taskId: "task-aime-sync", pinned: false, hidden: false, displayPriority: 1 },
  ],
  tracks: [
    {
      id: "track-aime-desktop",
      name: "Aime Desktop MVP",
      linkedTaskIds: ["task-aime-spec", "task-aime-widget", "task-aime-sync"],
      mode: "auto",
      pinned: true,
      targetDate: "2026-07-05",
      updatedAt: "2026-06-23T09:00:00.000Z",
    },
    {
      id: "track-q3-launch",
      name: "Q3 Launch",
      linkedTaskIds: ["task-aime-spec"],
      mode: "manual",
      manualPercent: 62,
      pinned: true,
      targetDate: "2026-07-31",
      updatedAt: "2026-06-23T09:00:00.000Z",
    },
  ],
  settings: {
    widgetX: 40,
    widgetY: 80,
    miniMode: false,
    reminderHour: 9,
    larkBaseUrl: "https://bytedance.larkoffice.com/base/F4k1bKUkRaIafPsKxP2cVAyEnwJ",
  },
};
